//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoryrServer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColoryrServer_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColoryrServer_Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColoryrServer.ColoryrServer.Resource", typeof(ColoryrServer_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似  的本地化字符串。
        /// </summary>
        internal static string AppDemoCS {
            get {
                return ResourceManager.GetString("AppDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.DllManager;
        ///using ColoryrServer.FileSystem;
        ///using ColoryrServer.Robot;
        ///using ColoryrServer.Utils;
        ///using ColoryrServer.WebSocket;
        ///using Newtonsoft.Json;
        ///using Newtonsoft.Json.Linq;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class ServerContentType
        ///    {
        ///        public const string JSON = &quot;application/json&quot;;
        ///        public const string XML = &quot;application/ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ColoryrSDK {
            get {
                return ResourceManager.GetString("ColoryrSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.DataBase;
        ///using MySql.Data.MySqlClient;
        ///using Oracle.ManagedDataAccess.Client;
        ///using System.Collections.Generic;
        ///using System.Data.SqlClient;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class Mysql
        ///    {
        ///        private string Database;
        ///        /// &lt;summary&gt;
        ///        /// Mysql数据库
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;Database&quot;&gt;数据库名&lt;/param&gt;
        ///        public Mysql(string Database)
        ///        {
        ///            if (MysqlCon.State == false)
        ///                throw new VarDump(&quot;M [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DatabaseSDK {
            get {
                return ResourceManager.GetString("DatabaseSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.29.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.29\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Text;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a complete HTML document.
        ///    public class HtmlDocument : IXPathNavigable
        ///    {
        ///        //
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlDocumentSDK {
            get {
                return ResourceManager.GetString("HtmlDocumentSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.29.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.29\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.CompilerServices;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents an HTML node.
        ///    [DebuggerDisplay(&quot;Name: {Origi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlNodeSDK {
            get {
                return ResourceManager.GetString("HtmlNodeSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.Html;
        ///using HtmlAgilityPack;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Net;
        ///using System.Net.Http;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class Html
        ///    {
        ///        private ExClient Http;
        ///        public CancellationTokenSource Cancel;
        ///        public CookieContainer Cookie;
        ///
        ///        public Html(CookieContainer Cookie = null,
        ///                    CancellationTokenSource Cancel = n [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlSDK {
            get {
                return ResourceManager.GetString("HtmlSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System.Collections.Generic;
        ///using System.Collections.Specialized;
        ///using System.IO;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class HttpRequest
        ///    {
        ///        public Dictionary&lt;string, dynamic&gt; Parameter { get; init; }
        ///        public NameValueCollection RowRequest { get; init; }//原始请求的字符串
        ///        public string Cookie { get; init; }
        ///        public MyContentType ContentType { get; init; }
        ///        public Stream Stream { get; init; }
        ///
        ///        /// 获取参数
        ///        /// &lt;/summary&gt;
        ///        /// &lt;para [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HttpSDK {
            get {
                return ResourceManager.GetString("HttpSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.IoT;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class TcpIoTRequest
        ///    {
        ///        public int Port { get; private set; }
        ///        public byte[] Data { get; private set; }
        ///        /// &lt;summary&gt;
        ///        /// 构造方法
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;Port&quot;&gt;IoT端口&lt;/param&gt;
        ///        /// &lt;param name=&quot;Data&quot;&gt;IoT发送的数据&lt;/param&gt;
        ///        public TcpIoTRequest(int Port, byte[] Data)
        ///        {
        ///            this.Port = Port;
        ///       [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IoTSDK {
            get {
                return ResourceManager.GetString("IoTSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Fleck, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
        ///// C:\Users\40206\.nuget\packages\fleck\1.1.0\lib\netcoreapp2.0\Fleck.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Threading.Tasks;
        ///
        ///namespace Fleck
        ///{
        ///    public interface IWebSocketConnection
        ///    {
        ///        Action OnOpen { get; set; }
        ///        Action OnClose { get; set; }
        ///        Action&lt;string&gt; OnMessage { get; set; }
        ///        Action&lt;byte[]&gt; OnBinary { get; set; }
        ///        Action&lt;byte[]&gt; OnPing { get; set; }
        ///        Action&lt;b [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IWebSocketConnectionSDK {
            get {
                return ResourceManager.GetString("IWebSocketConnectionSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 MySql.Data, Version=8.0.23.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d
        ///// C:\Users\40206\.nuget\packages\mysql.data\8.0.23\lib\net5.0\MySql.Data.dll
        ///#endregion
        ///
        ///using System;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Data.Common;
        ///
        ///namespace MySql.Data.MySqlClient
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a SQL statement to execute against a MySQL database. This class cannot
        ///    //     be inherited.
        ///    //
        ///    // 言论：
        ///    //     MySqlCommand features the [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MySqlCommandSDK {
            get {
                return ResourceManager.GetString("MySqlCommandSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Oracle.ManagedDataAccess, Version=2.0.19.1, Culture=neutral, PublicKeyToken=89b483f429c47342
        ///// C:\Users\40206\.nuget\packages\oracle.manageddataaccess.core\2.19.101\lib\netstandard2.0\Oracle.ManagedDataAccess.dll
        ///#endregion
        ///
        ///using Oracle.ManagedDataAccess.Types;
        ///using System;
        ///using System.ComponentModel;
        ///using System.ComponentModel.Design;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.IO;
        ///using System.Xml;
        ///
        ///namespace Oracle.ManagedDataAccess.Client
        ///{
        ///    [Designer(&quot;Or [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OracleCommandSDK {
            get {
                return ResourceManager.GetString("OracleCommandSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.Robot;
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class RobotAfter
        ///    {
        ///        public enum MessageType
        ///        {
        ///            group, private_, friend
        ///        }
        ///        public long qq { get; private set; }
        ///        public MessageType type { get; private set; }
        ///        public long id { get; private set; }
        ///        public long fid { get; private set; }
        ///        public bool res { get; private set; }
        ///        public string error { g [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RobotSDK {
            get {
                return ResourceManager.GetString("RobotSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 System.Data.SqlClient, Version=4.6.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        ///// C:\Users\40206\.nuget\packages\system.data.sqlclient\4.8.2\ref\netcoreapp2.1\System.Data.SqlClient.dll
        ///#endregion
        ///
        ///using System.Data.Common;
        ///using System.Data.Sql;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using System.Xml;
        ///
        ///namespace System.Data.SqlClient
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a Transact-SQL statement or stored procedure to execute against a
        ///    //     SQL S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SqlCommandSDK {
            get {
                return ResourceManager.GetString("SqlCommandSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using Fleck;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class WebSocketMessage
        ///    {
        ///        public IWebSocketConnection Client { get; private set; }
        ///        public string Data { get; private set; }
        ///        /// &lt;summary&gt;
        ///        /// WebSocket传来数据
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;Client&quot;&gt;WS客户端&lt;/param&gt;
        ///        /// &lt;param name=&quot;Data&quot;&gt;WS本次传来的数据&lt;/param&gt;
        ///        public WebSocketMessage(IWebSocketConnection Client, string Data)
        ///        {
        ///            this.Client = Client;
        ///            t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebSocketSDK {
            get {
                return ResourceManager.GetString("WebSocketSDK", resourceCulture);
            }
        }
    }
}
