//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoryrServer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColoryrServer_Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColoryrServer_Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColoryrServer.ColoryrServer.Resource", typeof(ColoryrServer_Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;ColoryrServer&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .center {
        ///            padding: 10px;
        ///            margin: 20px auto;
        ///            font-size: 40px;
        ///            text-align: center;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div class=&quot;center&quot;&gt;
        ///        404 NotFound
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string _404Html {
            get {
                return ResourceManager.GetString("404Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ﻿using System;
        ///using System.IO;
        ///using Xamarin.Forms;
        ///using Xamarin.Forms.Xaml;
        ///
        ///namespace ColoryrApp
        ///{
        ///    class test
        ///    {
        ///        public ContentPage Page { get; private set; }
        ///        private string Local;
        ///
        ///        private Button Button;
        ///        private Label Label;
        ///        private Entry Entry;
        ///        public bool Init(string local)
        ///        {
        ///            Local = local;
        ///            string pageXAML = &quot;&quot;;
        ///            var XamlFile = Path.Combine(local, &quot;main.xaml&quot;);
        ///            if (File.Ex [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AppDemoCS {
            get {
                return ResourceManager.GetString("AppDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///    &quot;Key&quot;: &quot;key&quot;,
        ///    &quot;Version&quot;: &quot;1.0.0&quot;,
        ///    &quot;Libs&quot;: []
        ///} 的本地化字符串。
        /// </summary>
        internal static string AppDemoJSON {
            get {
                return ResourceManager.GetString("AppDemoJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;ContentPage xmlns=&quot;http://xamarin.com/schemas/2014/forms&quot; xmlns:x=&quot;http://schemas.microsoft.com/winfx/2009/xaml&quot; x:Class=&quot;App2.MainPage&quot;&gt;
        ///	&lt;StackLayout HorizontalOptions=&quot;Center&quot;&gt;
        ///		&lt;Label Text=&quot;Hello World&quot; FontSize=&quot;Title&quot; Padding=&quot;30,10,30,10&quot; HorizontalOptions=&quot;Center&quot; HorizontalTextAlignment=&quot;Center&quot; x:Name=&quot;Label&quot; WidthRequest=&quot;500&quot;/&gt;
        ///		&lt;Button Text=&quot;Load&quot; x:Name=&quot;Button&quot; /&gt;
        ///		&lt;Entry Placeholder=&quot;Enter text&quot; x:Name=&quot;Entry&quot; /&gt;
        ///	&lt;/StackLayout&gt;
        ///&lt;/ContentPage [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string AppDemoXAML {
            get {
                return ResourceManager.GetString("AppDemoXAML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///namespace ColoryrServer
        ///{
        ///    public class {name}
        ///    {
        ///        public {name}()
        ///        {
        ///             
        ///        }
        ///
        ///        public string getString(string data)
        ///        {
        ///            return data + &quot;test&quot;;
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string ClassDemoCS {
            get {
                return ResourceManager.GetString("ClassDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.DllManager;
        ///using ColoryrServer.FileSystem;
        ///using ColoryrServer.Robot;
        ///using ColoryrServer.Utils;
        ///using ColoryrServer.WebSocket;
        ///using Newtonsoft.Json;
        ///using Newtonsoft.Json.Linq;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Security.Cryptography;
        ///using System.Text;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class HttpMultipartFile
        ///    {
        ///        public Stream Data { get; set; }
        ///        public string FileName { get; set; }
        ///    }
        ///    publ [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ColoryrSDK {
            get {
                return ResourceManager.GetString("ColoryrSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.DataBase;
        ///using MySql.Data.MySqlClient;
        ///using Oracle.ManagedDataAccess.Client;
        ///using System.Collections.Generic;
        ///using System.Data.SqlClient;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class Mysql
        ///    {
        ///        private string Database;
        ///        private int ID;
        ///        /// &lt;summary&gt;
        ///        /// Mysql数据库
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;Database&quot;&gt;数据库名&lt;/param&gt;
        ///        /// &lt;param name=&quot;ID&quot;&gt;数据库ID&lt;/param&gt;
        ///        public Mysql(string Database, int ID = 0)
        ///         [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DatabaseSDK {
            get {
                return ResourceManager.GetString("DatabaseSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///namespace ColoryrServer
        ///{
        ///    public class app_{name}
        ///    {
        ///        [NotesSDK(&quot;一个接口&quot;, new string[1]{ &quot;输入&quot; }, new string[1]{ &quot;输出&quot; })]
        ///        public dynamic {main}(HttpRequest http)
        ///        {  
        ///            return &quot;true&quot;;
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string DllDemoCS {
            get {
                return ResourceManager.GetString("DllDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;测试&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;script src=&quot;https://cdn.jsdelivr.net/npm/vue/dist/vue.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;https://unpkg.com/axios/dist/axios.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div id=&quot;app&quot;&gt;
        ///        &lt;h1&gt;Bitcoin Price Index&lt;/h1&gt;
        ///        &lt;section v-if=&quot;errored&quot;&gt;
        ///            &lt;p&gt;We&apos;re sorry, we&apos;re not able to retrieve this information at the moment, please try back later&lt;/p&gt;
        ///        &lt;/section&gt;
        ///        &lt;section v-else&gt;
        ///            &lt;div v [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlDemoHtml {
            get {
                return ResourceManager.GetString("HtmlDemoHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.29.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.29\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Text;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a complete HTML document.
        ///    public class HtmlDocument : IXPathNavigable
        ///    {
        ///        //
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlDocumentSDK {
            get {
                return ResourceManager.GetString("HtmlDocumentSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.29.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.29\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.CompilerServices;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents an HTML node.
        ///    [DebuggerDisplay(&quot;Name: {Origi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlNodeSDK {
            get {
                return ResourceManager.GetString("HtmlNodeSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.Html;
        ///using HtmlAgilityPack;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Linq;
        ///using System.Net;
        ///using System.Net.Http;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class HttpHtml : IDisposable
        ///    {
        ///        private ExClient Http;
        ///        public CancellationTokenSource Cancel;
        ///        public CookieContainer Cookie;
        ///
        ///        public HttpHtml(CookieContainer Cookie = null,
        ///                    Cancellation [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlSDK {
            get {
                return ResourceManager.GetString("HtmlSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System.Collections.Generic;
        ///using System.Collections.Specialized;
        ///using System.IO;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class HttpRequest
        ///    {
        ///        public Dictionary&lt;string, dynamic&gt; Parameter { get; init; }
        ///        public NameValueCollection RowRequest { get; init; }//原始请求的字符串
        ///        public string Cookie { get; init; }
        ///        public MyContentType ContentType { get; init; }
        ///        public Stream Stream { get; init; }
        ///
        ///        /// 获取参数
        ///        /// &lt;/summary&gt;
        ///        /// &lt;para [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HttpSDK {
            get {
                return ResourceManager.GetString("HttpSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function start() {
        ///    new Vue({
        ///        el: &apos;#app&apos;,
        ///        data() {
        ///            return {
        ///                info: null,
        ///                loading: true,
        ///                errored: false
        ///            }
        ///        },
        ///        filters: {
        ///            currencydecimal(value) {
        ///                return value.toFixed(2)
        ///            }
        ///        },
        ///        mounted() {
        ///            axios
        ///                .get(&apos;https://api.coindesk.com/v1/bpi/currentprice.json&apos;)
        ///                .then(response =&gt; {
        ///                   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IndexDemoJS {
            get {
                return ResourceManager.GetString("IndexDemoJS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;ColoryrServer&lt;/title&gt;
        ///    &lt;style&gt;
        ///        .center {
        ///            padding: 10px;
        ///            margin: 20px auto;
        ///            font-size: 40px;
        ///            text-align: center;
        ///        }
        ///    &lt;/style&gt;
        ///&lt;/head&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div class=&quot;center&quot;&gt;
        ///        欢迎使用ColoryrServer
        ///    &lt;/div&gt;
        ///&lt;/body&gt;
        ///
        ///&lt;/html&gt; 的本地化字符串。
        /// </summary>
        internal static string IndexHtml {
            get {
                return ResourceManager.GetString("IndexHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///namespace ColoryrServer
        ///{
        ///    public class {name}
        ///    {
        ///        public void {IoTTcp}(TcpIoTRequest head)
        ///        {
        ///                
        ///        }
        ///        public void {IoTUdp}(UdpIoTRequest head)
        ///        {
        ///                
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string IoTDemoCS {
            get {
                return ResourceManager.GetString("IoTDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.IoT;
        ///using System.Collections.Generic;
        ///using System.Text;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class TcpIoTRequest
        ///    {
        ///        private int Server { get; init; }
        ///        public int Port { get; init; }
        ///        public byte[] Data { get; init; }
        ///        /// &lt;summary&gt;
        ///        /// 构造方法
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;Port&quot;&gt;IoT端口&lt;/param&gt;
        ///        /// &lt;param name=&quot;Data&quot;&gt;IoT发送的数据&lt;/param&gt;
        ///        public TcpIoTRequest(int Port, byte[] Data, int Server)
        ///        [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IoTSDK {
            get {
                return ResourceManager.GetString("IoTSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Fleck, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
        ///// C:\Users\40206\.nuget\packages\fleck\1.1.0\lib\netcoreapp2.0\Fleck.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Threading.Tasks;
        ///
        ///namespace Fleck
        ///{
        ///    public interface IWebSocketConnection
        ///    {
        ///        Action OnOpen { get; set; }
        ///        Action OnClose { get; set; }
        ///        Action&lt;string&gt; OnMessage { get; set; }
        ///        Action&lt;byte[]&gt; OnBinary { get; set; }
        ///        Action&lt;byte[]&gt; OnPing { get; set; }
        ///        Action&lt;b [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IWebSocketConnectionSDK {
            get {
                return ResourceManager.GetString("IWebSocketConnectionSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///namespace ColoryrServer
        ///{
        ///    public class {name}
        ///    {
        ///        public void {MQTTMessage}(MqttMessage head)
        ///        {
        ///             
        ///        }
        ///        public void {MQTTValidator}(MqttConnectionValidator head)
        ///        {
        ///             
        ///        }
        ///        public void {MQTTSubscription}(MqttSubscription head)
        ///        {
        ///            
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string MqttDemoCS {
            get {
                return ResourceManager.GetString("MqttDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.MQTT;
        ///using MQTTnet.Protocol;
        ///using MQTTnet.Server;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class MqttConnectionValidator
        ///    {
        ///        public MqttConnectionValidatorContext Context { get; init; }
        ///        /// &lt;summary&gt;
        ///        /// MQTT服务器验证
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;Context&quot;&gt;数据&lt;/param&gt;
        ///        public MqttConnectionValidator(MqttConnectionValidatorContext Context)
        ///            =&gt; this.Context = Context;
        ///        /// &lt;summary&gt;
        ///        /// 发送消息
        ///        [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttSDK {
            get {
                return ResourceManager.GetString("MqttSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 MySql.Data, Version=8.0.23.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d
        ///// C:\Users\40206\.nuget\packages\mysql.data\8.0.23\lib\net5.0\MySql.Data.dll
        ///#endregion
        ///
        ///using System;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Data.Common;
        ///
        ///namespace MySql.Data.MySqlClient
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a SQL statement to execute against a MySQL database. This class cannot
        ///    //     be inherited.
        ///    //
        ///    // 言论：
        ///    //     MySqlCommand features the [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MySqlCommandSDK {
            get {
                return ResourceManager.GetString("MySqlCommandSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    [AttributeUsage(AttributeTargets.Method, AllowMultiple = false)]
        ///    public class NotesSDK : Attribute
        ///    {
        ///        public string Text;
        ///        public string[] Input;
        ///        public string[] Output;
        ///
        ///        public NotesSDK(string Text, string[] Input = null, string[] Output = null)
        ///        {
        ///            this.Text = Text;
        ///            this.Input = Input ?? new string[1];
        ///            this.Output = Output ?? new string[1];
        ///        }
        ///    }
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string NotesSDK {
            get {
                return ResourceManager.GetString("NotesSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Oracle.ManagedDataAccess, Version=2.0.19.1, Culture=neutral, PublicKeyToken=89b483f429c47342
        ///// C:\Users\40206\.nuget\packages\oracle.manageddataaccess.core\2.19.101\lib\netstandard2.0\Oracle.ManagedDataAccess.dll
        ///#endregion
        ///
        ///using Oracle.ManagedDataAccess.Types;
        ///using System;
        ///using System.ComponentModel;
        ///using System.ComponentModel.Design;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.IO;
        ///using System.Xml;
        ///
        ///namespace Oracle.ManagedDataAccess.Client
        ///{
        ///    [Designer(&quot;Or [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OracleCommandSDK {
            get {
                return ResourceManager.GetString("OracleCommandSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///namespace ColoryrServer
        ///{
        ///    public class {name}
        ///    {
        ///        public void {RobotMessage}(RobotRequest head)
        ///        {
        ///             
        ///        }
        ///        public void {RobotSend}(RobotAfter head)
        ///        {
        ///             
        ///        }
        ///        public void {RobotEvent}(RobotEvent head)
        ///        {
        ///            
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string RobotDemoCS {
            get {
                return ResourceManager.GetString("RobotDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using System.Collections.Concurrent;
        ///using System.Collections.Generic;
        ///
        ///namespace ColoryrServer.Robot
        ///{
        ///    /// &lt;summary&gt;
        ///    /// 55 [插件]获取群列表
        ///    /// &lt;/summary&gt;
        ///    public record ListGroupPack : PackBase
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 群列表
        ///        /// &lt;/summary&gt;
        ///        public List&lt;GroupInfo&gt; groups { get; set; }
        ///    }
        ///    /// &lt;summary&gt;
        ///    /// 56 [插件]获取好友列表
        ///    /// &lt;/summary&gt;
        ///    public record ListFriendPack : PackBase
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 朋友列 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RobotPacks {
            get {
                return ResourceManager.GetString("RobotPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.Robot;
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class RobotAfter
        ///    {
        ///        public enum MessageType
        ///        {
        ///            group, private_, friend
        ///        }
        ///        public long qq { get; private set; }
        ///        public MessageType type { get; private set; }
        ///        public long id { get; private set; }
        ///        public long fid { get; private set; }
        ///        public bool res { get; private set; }
        ///        public string error { g [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RobotSDK {
            get {
                return ResourceManager.GetString("RobotSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 System.Data.SqlClient, Version=4.6.1.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        ///// C:\Users\40206\.nuget\packages\system.data.sqlclient\4.8.2\ref\netcoreapp2.1\System.Data.SqlClient.dll
        ///#endregion
        ///
        ///using System.Data.Common;
        ///using System.Data.Sql;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using System.Xml;
        ///
        ///namespace System.Data.SqlClient
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a Transact-SQL statement or stored procedure to execute against a
        ///    //     SQL S [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SqlCommandSDK {
            get {
                return ResourceManager.GetString("SqlCommandSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///namespace ColoryrServer
        ///{
        ///    public class {name}
        ///    {
        ///        public void {TaskRun}(object[] args)
        ///        {
        ///             
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string TaskDemoCS {
            get {
                return ResourceManager.GetString("TaskDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.TaskUtils;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class TaskSDK
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 是否存在任务
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;name&quot;&gt;任务名字&lt;/param&gt;
        ///        /// &lt;returns&gt;是否存在&lt;/returns&gt;
        ///        public static bool HaveTask(string name)
        ///            =&gt; TaskThread.HaveTask(name);
        ///        /// &lt;summary&gt;
        ///        /// 添加一个任务
        ///        /// 如果存在则会覆盖
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;arg&quot;&gt;任务参数&lt;/param&gt;
        ///        public static bool StartTask(T [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string TaskSDK {
            get {
                return ResourceManager.GetString("TaskSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.FileSystem;
        ///using System;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class WebHtml
        ///    {
        ///        /// &lt;summary&gt;
        ///        /// 向前端添加Web资源
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;uuid&quot;&gt;资源UUID&lt;/param&gt;
        ///        /// &lt;param name=&quot;name&quot;&gt;名字&lt;/param&gt;
        ///        /// &lt;param name=&quot;code&quot;&gt;内容&lt;/param&gt;
        ///        public static void AddHtml(string uuid, string name, string code)
        ///        {
        ///            var web = HtmlUtils.GetHtml(uuid);
        ///            if (web == null)
        ///            {
        ///               [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebHtmlSDK {
            get {
                return ResourceManager.GetString("WebHtmlSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///namespace ColoryrServer
        ///{
        ///    public class {name}
        ///    {
        ///        public void {WebSocketMessage}(WebSocketMessage head)
        ///        {
        ///             
        ///        }
        ///        public void {WebSocketOpen}(WebSocketOpen head)
        ///        {
        ///             
        ///        }
        ///        public void {WebSocketClose}(WebSocketClose head)
        ///        {
        ///            
        ///        }
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string WebSocketDemoCS {
            get {
                return ResourceManager.GetString("WebSocketDemoCS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.WebSocket;
        ///using Fleck;
        ///
        ///namespace ColoryrServer.SDK
        ///{
        ///    public class WebSocketMessage
        ///    {
        ///        public bool IsAvailable { get; init; }
        ///        public IWebSocketConnectionInfo Info { get; init; }
        ///        public string Data { get; init; }
        ///        private int Server { get; init; }
        ///        /// &lt;summary&gt;
        ///        /// WebSocket传来数据
        ///        /// &lt;/summary&gt;
        ///        /// &lt;param name=&quot;Client&quot;&gt;WS客户端&lt;/param&gt;
        ///        /// &lt;param name=&quot;Data&quot;&gt;WS本次传来的数据&lt;/param&gt;
        ///        public WebSocke [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebSocketSDK {
            get {
                return ResourceManager.GetString("WebSocketSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 ICSharpCode.SharpZipLib, Version=1.3.2.10, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
        ///// E:\NuGet\packages\sharpziplib\1.3.2\lib\netstandard2.1\ICSharpCode.SharpZipLib.dll
        ///#endregion
        ///
        ///using System;
        ///
        ///namespace ICSharpCode.SharpZipLib.Zip
        ///{
        ///    //
        ///    // 摘要:
        ///    //     This class represents an entry in a zip archive. This can be a file or a directory
        ///    //     ZipFile and ZipInputStream will give you instances of this class as information
        ///    //     about the members in an archi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ZipEntrySDK {
            get {
                return ResourceManager.GetString("ZipEntrySDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 ICSharpCode.SharpZipLib, Version=1.3.2.10, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
        ///// E:\NuGet\packages\sharpziplib\1.3.2\lib\netstandard2.1\ICSharpCode.SharpZipLib.dll
        ///#endregion
        ///
        ///using ICSharpCode.SharpZipLib.Zip.Compression.Streams;
        ///using System.IO;
        ///
        ///namespace ICSharpCode.SharpZipLib.Zip
        ///{
        ///    //
        ///    // 摘要:
        ///    //     This is an InflaterInputStream that reads the files baseInputStream an zip archive
        ///    //     one after another. It has a special method to get the zip entr [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ZipInputStreamSDK {
            get {
                return ResourceManager.GetString("ZipInputStreamSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 ICSharpCode.SharpZipLib, Version=1.3.2.10, Culture=neutral, PublicKeyToken=1b03e6acf1164f73
        ///// E:\NuGet\packages\sharpziplib\1.3.2\lib\netstandard2.1\ICSharpCode.SharpZipLib.dll
        ///#endregion
        ///
        ///using ICSharpCode.SharpZipLib.Core;
        ///using ICSharpCode.SharpZipLib.Zip.Compression.Streams;
        ///using System.IO;
        ///
        ///namespace ICSharpCode.SharpZipLib.Zip
        ///{
        ///    //
        ///    // 摘要:
        ///    //     This is a DeflaterOutputStream that writes the files into a zip archive one after
        ///    //     another. It has a special  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string ZipOutputStreamSDK {
            get {
                return ResourceManager.GetString("ZipOutputStreamSDK", resourceCulture);
            }
        }
    }
}
