//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoryrServer {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ColorResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ColorResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColoryrServer.ColorResource", typeof(ColorResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using ColorServer;
        ///using ColorServer.DataBase;
        ///using ColorServer.DllManager;
        ///using ColorServer.Http;
        ///using ColorServer.IoT;
        ///using ColorServer.Robot;
        ///using ColorServer.Utils;
        ///using ColorServer.WebSocket;
        ///using Fleck;
        ///using HtmlAgilityPack;
        ///using MySql.Data.MySqlClient;
        ///using Newtonsoft.Json;
        ///using Newtonsoft.Json.Linq;
        ///using Oracle.ManagedDataAccess.Client;
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Collections.Specialized;
        ///using System.Data;
        ///using System.Data.SqlClient;
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.24.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.24\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.CompilerServices;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents an HTML node.
        ///    [DebuggerDisplay(&quot;Name: {Origi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api1 {
            get {
                return ResourceManager.GetString("api1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.24.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.24\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a combined list and collection of HTML nodes.
        ///    [DefaultMember(&quot;Item&quot;)]
        ///    public class HtmlNod [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api2 {
            get {
                return ResourceManager.GetString("api2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.24.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.24\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a combined list and collection of HTML nodes.
        ///    [DefaultMember(&quot;Item&quot;)]
        ///    public class HtmlAtt [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api3 {
            get {
                return ResourceManager.GetString("api3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
        ///// C:\Users\40206\.nuget\packages\newtonsoft.json\12.0.3\lib\netstandard2.0\Newtonsoft.Json.dll
        ///#endregion
        ///
        ///using Newtonsoft.Json;
        ///using Newtonsoft.Json.Linq;
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Diagnostics.CodeAnalysis;
        ///using System.Dynamic;
        ///using System.Linq.Expressions;
        ///using System.Reflection;
        ///using System.Runtime.Co [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api4 {
            get {
                return ResourceManager.GetString("api4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
        ///// C:\Users\40206\.nuget\packages\newtonsoft.json\12.0.3\lib\netstandard2.0\Newtonsoft.Json.dll
        ///#endregion
        ///
        ///using Newtonsoft.Json;
        ///using Newtonsoft.Json.Linq;
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Diagnostics.CodeAnalysis;
        ///using System.Dynamic;
        ///using System.Linq.Expressions;
        ///using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System. [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api5 {
            get {
                return ResourceManager.GetString("api5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46
        ///// C:\Users\40206\.nuget\packages\stackexchange.redis\2.1.58\lib\netstandard2.0\StackExchange.Redis.dll
        ///#endregion
        ///
        ///using StackExchange.Redis;
        ///using System;
        ///using System.IO;
        ///
        ///namespace StackExchange.Redis
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents values that can be stored in redis
        ///    public readonly struct RedisValue : IEquatable&lt;RedisValue&gt;, IComparable&lt;RedisValue&gt;, IComparable, IConvertible
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api6 {
            get {
                return ResourceManager.GetString("api6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 MySql.Data, Version=8.0.21.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d
        ///// C:\Users\40206\.nuget\packages\mysql.data\8.0.21\lib\netstandard2.1\MySql.Data.dll
        ///#endregion
        ///
        ///using MySql.Data.MySqlClient;
        ///using System;
        ///using System.ComponentModel;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Data.Common;
        ///
        ///namespace MySql.Data.MySqlClient
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a SQL statement to execute against a MySQL database. This class cannot
        ///    //     be [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api7 {
            get {
                return ResourceManager.GetString("api7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Fleck, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null
        ///// C:\Users\40206\.nuget\packages\fleck\1.1.0\lib\netcoreapp2.0\Fleck.dll
        ///#endregion
        ///
        ///using Fleck;
        ///using System;
        ///using System.Threading.Tasks;
        ///
        ///namespace Fleck
        ///{
        ///    public interface IWebSocketConnection
        ///    {
        ///        Action OnOpen { get; set; }
        ///        Action OnClose { get; set; }
        ///        Action&lt;string&gt; OnMessage { get; set; }
        ///        Action&lt;byte[]&gt; OnBinary { get; set; }
        ///        Action&lt;byte[]&gt; OnPing { get; set; }
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api8 {
            get {
                return ResourceManager.GetString("api8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.24.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.24\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Text;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a complete HTML document.
        ///    public class HtmlDocument : IXPathNavigable
        ///    {
        ///        //
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string api9 {
            get {
                return ResourceManager.GetString("api9", resourceCulture);
            }
        }
    }
}
