//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoryrServer.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoWebResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoWebResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColoryrServer.Core.DemoWebResource", typeof(DemoWebResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;测试&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;script src=&quot;https://cdn.jsdelivr.net/npm/vue/dist/vue.js&quot;&gt;&lt;/script&gt;
        ///&lt;script src=&quot;https://unpkg.com/axios/dist/axios.min.js&quot;&gt;&lt;/script&gt;
        ///
        ///&lt;body&gt;
        ///    &lt;div id=&quot;app&quot;&gt;
        ///        &lt;h1&gt;Bitcoin Price Index&lt;/h1&gt;
        ///        &lt;section v-if=&quot;errored&quot;&gt;
        ///            &lt;p&gt;We&apos;re sorry, we&apos;re not able to retrieve this information at the moment, please try back later&lt;/p&gt;
        ///        &lt;/section&gt;
        ///        &lt;section v-else&gt;
        ///            &lt;div v [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlDemoHtml {
            get {
                return ResourceManager.GetString("HtmlDemoHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function start() {
        ///    new Vue({
        ///        el: &apos;#app&apos;,
        ///        data() {
        ///            return {
        ///                info: null,
        ///                loading: true,
        ///                errored: false
        ///            }
        ///        },
        ///        filters: {
        ///            currencydecimal(value) {
        ///                return value.toFixed(2)
        ///            }
        ///        },
        ///        mounted() {
        ///            axios
        ///                .get(&apos;https://api.coindesk.com/v1/bpi/currentprice.json&apos;)
        ///                .then(response =&gt; {
        ///                   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IndexDemoJS {
            get {
                return ResourceManager.GetString("IndexDemoJS", resourceCulture);
            }
        }
    }
}
