//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoryrServer.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColoryrServer.Core.DemoResource", typeof(DemoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///public class {name}
        ///{
        ///    public {name}()
        ///    {
        ///             
        ///    }
        ///
        ///    public string getString(string data)
        ///    {
        ///        return data + &quot;test&quot;;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///public class app_{name}
        ///{
        ///    public void debug(){}//如果加上这个函数则报错输出至网页
        ///    [NotesSDK(&quot;一个接口&quot;, new string[1]{ &quot;输入&quot; }, new string[1]{ &quot;输出&quot; })]
        ///    public dynamic Main(HttpRequest http)
        ///    {  
        ///        return &quot;true&quot;;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Dll {
            get {
                return ResourceManager.GetString("Dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///public class {name}
        ///{
        ///    public bool OnMessage(MqttMessage head)
        ///    {
        ///        return true;
        ///    }
        ///    public bool OnValidator(MqttConnectionValidator head)
        ///    {
        ///        return true;
        ///    }
        ///    public bool OnSubscription(MqttSubscription head)
        ///    {
        ///        return true;
        ///    }
        ///    public bool OnUnsubscription(MqttUnsubscription head)
        ///    {
        ///        return true;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Mqtt {
            get {
                return ResourceManager.GetString("Mqtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///public class {name}
        ///{
        ///    public void OnMessage(RobotRequest head)
        ///    {
        ///             
        ///    }
        ///    public void OnMessagSend(RobotAfter head)
        ///    {
        ///             
        ///    }
        ///    public void OnRobotEvent(RobotEvent head)
        ///    {
        ///            
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///public class {name}
        ///{
        ///    public void OnTcpMessage(TcpSocketRequest head)
        ///    {
        ///                
        ///    }
        ///    public void OnUdpMessage(UdpSocketRequest head)
        ///    {
        ///                
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Socket {
            get {
                return ResourceManager.GetString("Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///public class {name}
        ///{
        ///    public TaskRes Run(object[] args)
        ///    {
        ///        return new() 
        ///        {
        ///            Res = true
        ///        };
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Task {
            get {
                return ResourceManager.GetString("Task", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        ///public class {name}
        ///{
        ///    public void OnMessage(WebSocketMessage head)
        ///    {
        ///             
        ///    }
        ///    public void OnOpen(WebSocketOpen head)
        ///    {
        ///             
        ///    }
        ///    public void OnClose(WebSocketClose head)
        ///    {
        ///            
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string WebSocket {
            get {
                return ResourceManager.GetString("WebSocket", resourceCulture);
            }
        }
    }
}
