//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoryrServer.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DemoResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DemoResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColoryrServer.Core.DemoResource", typeof(DemoResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[ClassIN]
        ///public class {name}
        ///{
        ///    public {name}()
        ///    {
        ///             
        ///    }
        ///
        ///    public string GetString(string data)
        ///    {
        ///        return data + &quot;test&quot;;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Class {
            get {
                return ResourceManager.GetString("Class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[DllIN(true)]//true则报错输出至网页
        ///public class App_{name}
        ///{
        ///    [NotesSDK(&quot;一个接口&quot;, new string[1]{ &quot;输入&quot; }, new string[1]{ &quot;输出&quot; })]
        ///    public dynamic Main(HttpDllRequest http)
        ///    {  
        ///        return &quot;true&quot;;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Dll {
            get {
                return ResourceManager.GetString("Dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[MqttIN]
        ///public class {name}
        ///{
        ///    public bool OnMessage(DllMqttMessage head)
        ///    {
        ///        return false; //true表示事件已处理完毕
        ///    }
        ///    public bool OnRetainedMessageChanged(DllMqttRetainedMessageChanged head)
        ///    {
        ///        return false;
        ///    }
        ///    public bool OnMessageLoading(DllMqttLoadingRetainedMessages head)
        ///    {
        ///        return false;
        ///    }
        ///    public bool OnValidator(DllMqttConnectionValidator head)
        ///    {
        ///        return false;
        ///    }
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Mqtt {
            get {
                return ResourceManager.GetString("Mqtt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///using System;
        ///using DotNetty.Transport.Channels;
        ///using DotNetty.Handlers.Logging;
        ///using DotNetty.Handlers.Tls;
        ///using DotNetty.Transport.Bootstrapping;
        ///using DotNetty.Transport.Channels.Sockets;
        ///using System.Security.Cryptography.X509Certificates;
        ///
        /////ColoryrServer_Debug
        ///
        ///[SocketIN(true)] //true表示为Netty类型
        ///public class {name} : INetty
        ///{
        ///    private IChannel bootstrapChannel;
        ///    public override void Start(MultithreadEventLoopGroup bossGroup, MultithreadEventLoopGroup wor [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Netty {
            get {
                return ResourceManager.GetString("Netty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[RobotIN(new int[] {})] //在这里添加更多订阅的事件
        ///public class {name}
        ///{
        ///    public bool OnMessage(RobotMessage head)
        ///    {
        ///        return false; //true表示事件已处理完毕
        ///    }
        ///    public bool OnMessagSend(RobotSend head)
        ///    {
        ///        return false;
        ///    }
        ///    //这里是更多事件的回调
        ///    public bool OnRobotEvent(RobotEvent head)
        ///    {
        ///        return false;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Robot {
            get {
                return ResourceManager.GetString("Robot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[ServiceIN(false, ServiceType.Normal)] //true表示跟随服务器启动
        ///public class {name}
        ///{
        ///    public ServiceNextState Run(object[] args, CancellationToken token)
        ///    {
        ///        return ServiceNextState.Stop;
        ///    }
        ///
        ///    public void OnStart()
        ///    {
        ///        
        ///    }
        ///
        ///    public void OnStop()
        ///    {
        ///        
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Service1 {
            get {
                return ResourceManager.GetString("Service1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[ServiceIN(type: ServiceType.ErrorDump)]
        ///public class {name}
        ///{
        ///    public bool OnError(Exception e)
        ///    {
        ///        return false;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Service2 {
            get {
                return ResourceManager.GetString("Service2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[ServiceIN(false, ServiceType.Normal)] //true表示跟随服务器启动
        ///public class {name}
        ///{
        ///    public ServiceNextState Run(object[] args, CancellationToken token)
        ///    {
        ///        return ServiceNextState.Stop;
        ///    }
        ///
        ///    public void OnStart()
        ///    {
        ///        
        ///    }
        ///
        ///    public void OnStop()
        ///    {
        ///        
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Service3 {
            get {
                return ResourceManager.GetString("Service3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using System;
        ///using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[ServiceIN(false, ServiceType.Normal)] //true表示跟随服务器启动
        ///public class {name}
        ///{
        ///    public ServiceNextState Run(object[] args, CancellationToken token)
        ///    {
        ///        return ServiceNextState.Stop;
        ///    }
        ///
        ///    public void OnStart()
        ///    {
        ///        
        ///    }
        ///
        ///    public void OnStop()
        ///    {
        ///        
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Service4 {
            get {
                return ResourceManager.GetString("Service4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[SocketIN]
        ///public class {name}
        ///{
        ///    public bool OnTcpMessage(SocketTcpRequest head)
        ///    {
        ///        return false; //true表示事件已处理完毕
        ///    }
        ///    public bool OnUdpMessage(SocketUdpRequest head)
        ///    {
        ///        return false;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string Socket {
            get {
                return ResourceManager.GetString("Socket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 using ColoryrServer.SDK;
        ///
        /////ColoryrServer_Debug
        ///
        ///[WebSocketIN]
        ///public class {name}
        ///{
        ///    public bool OnMessage(WebSocketMessage head)
        ///    {
        ///        return false; //true表示事件已处理完毕
        ///    }
        ///    public bool OnOpen(WebSocketOpen head)
        ///    {
        ///        return false;
        ///    }
        ///    public bool OnClose(WebSocketClose head)
        ///    {
        ///        return false;
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string WebSocket {
            get {
                return ResourceManager.GetString("WebSocket", resourceCulture);
            }
        }
    }
}
