//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ColoryrServer.Core {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OtherSDKResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OtherSDKResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ColoryrServer.Core.OtherSDKResource", typeof(OtherSDKResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.43.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.43\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Runtime.CompilerServices;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents an HTML node.
        ///    [DebuggerDisplay(&quot;Name: {Origi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlDll {
            get {
                return ResourceManager.GetString("HtmlDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 HtmlAgilityPack, Version=1.11.43.0, Culture=neutral, PublicKeyToken=bd319b19eaf3b43a
        ///// C:\Users\40206\.nuget\packages\htmlagilitypack\1.11.43\lib\netstandard2.0\HtmlAgilityPack.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///using System.IO;
        ///using System.Text;
        ///using System.Xml;
        ///using System.Xml.XPath;
        ///
        ///namespace HtmlAgilityPack
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a complete HTML document.
        ///    public class HtmlDocument : IXPathNavigable
        ///    {
        ///        //
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string HtmlDll1 {
            get {
                return ResourceManager.GetString("HtmlDll1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class LoadingRetainedMessagesEventArgs : EventArgs
        ///    {
        ///        public List&lt;MqttApplicationMessage&gt; LoadedRetainedMessages { get; set; } = new List&lt;MqttApplicationMessage&gt;();
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string MqttDll {
            get {
                return ResourceManager.GetString("MqttDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 MQTTnet, Version=4.0.1.184, Culture=neutral, PublicKeyToken=fdb7629f2e364a63
        ///// C:\Users\40206\.nuget\packages\mqttnet\4.0.1.184\lib\net6.0\MQTTnet.dll
        ///#endregion
        ///
        ///using MQTTnet.Adapter;
        ///using MQTTnet.Formatter;
        ///using MQTTnet.Packets;
        ///using MQTTnet.Protocol;
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Security.Cryptography.X509Certificates;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class ValidatingConnectionEventArgs : EventArgs
        ///     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll1 {
            get {
                return ResourceManager.GetString("MqttDll1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///namespace MQTTnet.Formatter
        ///{
        ///    public enum MqttProtocolVersion
        ///    {
        ///        Unknown = 0,
        ///
        ///        V310 = 3,
        ///        V311 = 4,
        ///        V500 = 5
        ///    }
        ///} 的本地化字符串。
        /// </summary>
        internal static string MqttDll10 {
            get {
                return ResourceManager.GetString("MqttDll10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public enum MqttClientDisconnectType
        ///    {
        ///        Clean,
        ///        NotClean,
        ///        Takeover
        ///    }
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string MqttDll11 {
            get {
                return ResourceManager.GetString("MqttDll11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System;
        ///using System.Collections;
        ///using System.Threading;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class InterceptingPublishEventArgs : EventArgs
        ///    {
        ///        public InterceptingPublishEventArgs(MqttApplicationMessage applicationMessage, CancellationToken cancellationToken, string clientId, IDic [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll12 {
            get {
                return ResourceManager.GetString("MqttDll12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System.Collections.Generic;
        ///using MQTTnet.Packets;
        ///using MQTTnet.Protocol;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class PublishResponse
        ///    {
        ///        public MqttPubAckReasonCode ReasonCode { get; set; } = MqttPubAckReasonCode.Success;
        ///        
        ///        public string ReasonString { get; set; }
        ///
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll13 {
            get {
                return ResourceManager.GetString("MqttDll13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class ApplicationMessageNotConsumedEventArgs : EventArgs
        ///    {
        ///        public ApplicationMessageNotConsumedEventArgs(MqttApplicationMessage applicationMessage, string senderId)
        ///        {
        ///            ApplicationMessage = applicationMessage ?? throw  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll14 {
            get {
                return ResourceManager.GetString("MqttDll14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class RetainedMessageChangedEventArgs : EventArgs
        ///    {
        ///        public string ClientId { get; internal set; }
        ///        
        ///        public MqttApplicationMessage ChangedRetainedMessage { get; internal set; }
        ///        
        ///   [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll2 {
            get {
                return ResourceManager.GetString("MqttDll2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 MQTTnet, Version=4.0.1.184, Culture=neutral, PublicKeyToken=fdb7629f2e364a63
        ///// C:\Users\40206\.nuget\packages\mqttnet\4.0.1.184\lib\net6.0\MQTTnet.dll
        ///#endregion
        ///
        ///using MQTTnet.Packets;
        ///using System;
        ///using System.Collections;
        ///using System.Collections.Generic;
        ///using System.Threading;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class InterceptingSubscriptionEventArgs : EventArgs
        ///    {
        ///        public InterceptingSubscriptionEventArgs();
        ///
        ///        //
        ///        // 摘要:
        ///        //     [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll3 {
            get {
                return ResourceManager.GetString("MqttDll3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 MQTTnet, Version=4.0.1.184, Culture=neutral, PublicKeyToken=fdb7629f2e364a63
        ///// C:\Users\40206\.nuget\packages\mqttnet\4.0.1.184\lib\net6.0\MQTTnet.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections;
        ///using System.Threading;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class InterceptingUnsubscriptionEventArgs : EventArgs
        ///    {
        ///        public InterceptingUnsubscriptionEventArgs();
        ///
        ///        //
        ///        // 摘要:
        ///        //     Gets the cancellation token which can indicate that th [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll4 {
            get {
                return ResourceManager.GetString("MqttDll4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System.Collections.Generic;
        ///using MQTTnet.Packets;
        ///using MQTTnet.Protocol;
        ///
        ///namespace MQTTnet
        ///{
        ///    public sealed class MqttApplicationMessage
        ///    {
        ///        /// &lt;summary&gt;
        ///        ///     Gets or sets the content type.
        ///        ///     The content type must be a UTF-8 encoded string. The content type va [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll5 {
            get {
                return ResourceManager.GetString("MqttDll5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///namespace MQTTnet.Protocol
        ///{
        ///    public enum MqttQualityOfServiceLevel
        ///    {
        ///        AtMostOnce = 0x00,
        ///        AtLeastOnce = 0x01,
        ///        ExactlyOnce = 0x02
        ///    }
        ///}
        /// 的本地化字符串。
        /// </summary>
        internal static string MqttDll6 {
            get {
                return ResourceManager.GetString("MqttDll6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///namespace MQTTnet.Protocol
        ///{
        ///    public enum MqttConnectReasonCode
        ///    {
        ///        Success = 0,
        ///        UnspecifiedError = 128,
        ///        MalformedPacket = 129,
        ///        ProtocolError = 130,
        ///        ImplementationSpecificError = 131,
        ///        UnsupportedProtocolVersion = 132,
        ///        ClientIdentifierNotValid = 13 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll7 {
            get {
                return ResourceManager.GetString("MqttDll7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System;
        ///using System.Collections;
        ///using MQTTnet.Formatter;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class ClientConnectedEventArgs : EventArgs
        ///    {
        ///        public ClientConnectedEventArgs(string clientId, string userName, MqttProtocolVersion protocolVersion, string endpoint, IDictionary sessionI [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll8 {
            get {
                return ResourceManager.GetString("MqttDll8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // Licensed to the .NET Foundation under one or more agreements.
        ///// The .NET Foundation licenses this file to you under the MIT license.
        ///// See the LICENSE file in the project root for more information.
        ///
        ///using System;
        ///using System.Collections;
        ///
        ///namespace MQTTnet.Server
        ///{
        ///    public sealed class ClientDisconnectedEventArgs : EventArgs
        ///    {
        ///        public ClientDisconnectedEventArgs(string clientId, MqttClientDisconnectType disconnectType, string endpoint, IDictionary sessionItems)
        ///        {
        ///            Clie [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MqttDll9 {
            get {
                return ResourceManager.GetString("MqttDll9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 MySql.Data, Version=8.0.29.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d
        ///// C:\Users\40206\.nuget\packages\mysql.data\8.0.29\lib\net6.0\MySql.Data.dll
        ///#endregion
        ///
        ///using System;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///using System.Transactions;
        ///
        ///namespace MySql.Data.MySqlClient
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a connection to a MySQL Server database. This class cannot be inherite [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string MysqlDll {
            get {
                return ResourceManager.GetString("MysqlDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Oracle.ManagedDataAccess, Version=3.1.21.1, Culture=neutral, PublicKeyToken=89b483f429c47342
        ///// C:\Users\40206\.nuget\packages\oracle.manageddataaccess.core\3.21.61\lib\netstandard2.1\Oracle.ManagedDataAccess.dll
        ///#endregion
        ///
        ///using System;
        ///using System.ComponentModel;
        ///using System.Data;
        ///using System.Data.Common;
        ///using System.Security;
        ///using System.Transactions;
        ///
        ///namespace Oracle.ManagedDataAccess.Client
        ///{
        ///    [DefaultEvent(&quot;InfoMessage&quot;)]
        ///    public sealed class OracleConnection : D [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string OracleDll {
            get {
                return ResourceManager.GetString("OracleDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 StackExchange.Redis, Version=2.0.0.0, Culture=neutral, PublicKeyToken=c219ff1ca8c2ce46
        ///// C:\Users\40206\.nuget\packages\stackexchange.redis\2.6.45\lib\net5.0\StackExchange.Redis.dll
        ///#endregion
        ///
        ///#nullable enable
        ///
        ///using StackExchange.Redis.Maintenance;
        ///using StackExchange.Redis.Profiling;
        ///using System;
        ///using System.ComponentModel;
        ///using System.IO;
        ///using System.Net;
        ///using System.Runtime.CompilerServices;
        ///using System.Threading.Tasks;
        ///
        ///namespace StackExchange.Redis
        ///{
        ///    //
        ///    // [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string RedisDll {
            get {
                return ResourceManager.GetString("RedisDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 System.Data.SqlClient, Version=4.6.1.3, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
        ///// C:\Users\40206\.nuget\packages\system.data.sqlclient\4.8.3\ref\netcoreapp2.1\System.Data.SqlClient.dll
        ///#endregion
        ///
        ///using System.Collections;
        ///using System.Data.Common;
        ///using System.Security;
        ///using System.Threading;
        ///using System.Threading.Tasks;
        ///
        ///namespace System.Data.SqlClient
        ///{
        ///    //
        ///    // 摘要:
        ///    //     Represents a connection to a SQL Server database. This class cannot be inherited.
        ///    [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string SqlClientDll {
            get {
                return ResourceManager.GetString("SqlClientDll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 #region 程序集 Fleck, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null
        ///// C:\Users\40206\.nuget\packages\fleck\1.2.0\lib\netcoreapp2.0\Fleck.dll
        ///#endregion
        ///
        ///using System;
        ///using System.Collections.Generic;
        ///
        ///namespace Fleck
        ///{
        ///    public interface IWebSocketConnectionInfo
        ///    {
        ///        string SubProtocol { get; }
        ///        string Origin { get; }
        ///        string Host { get; }
        ///        string Path { get; }
        ///        string ClientIpAddress { get; }
        ///        int ClientPort { get; }
        ///        IDictionary&lt; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string WebSocketDll {
            get {
                return ResourceManager.GetString("WebSocketDll", resourceCulture);
            }
        }
    }
}
